/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
/* tslint:disable */
import React, { useState } from 'react';
import { generateImage } from '../services/geminiService';

export const ImageStudio: React.FC = () => {
    const [prompt, setPrompt] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [imageUrl, setImageUrl] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            setError('Please enter a prompt.');
            return;
        }
        setIsLoading(true);
        setError(null);
        
        try {
            const url = await generateImage(prompt);
            setImageUrl(url);
        } catch (e: any) {
            console.error(e);
            setError(e.message || 'Failed to generate image. Please try again.');
            setImageUrl(null); // Clear image on error
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = () => {
        if (!imageUrl) return;
        const link = document.createElement('a');
        link.href = imageUrl;
        const filename = prompt.trim().toLowerCase().replace(/\s+/g, '-').slice(0, 50) || 'gemini-generated-image';
        link.download = `${filename}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handleShare = async () => {
        if (!imageUrl) return;
        if (!navigator.share) {
            setError('Web Share API is not supported in this browser.');
            return;
        }

        try {
            const response = await fetch(imageUrl);
            const blob = await response.blob();
            const file = new File([blob], 'gemini-image.png', { type: blob.type });

            await navigator.share({
                title: 'Image generated by G OS',
                text: `Check out this image I created: "${prompt}"`,
                files: [file],
            });
        } catch (err) {
            console.error('Error sharing the image:', err);
             if ((err as Error).name !== 'AbortError') {
                setError('Could not share the image.');
            }
        }
    };

    return (
        <div className="p-6 bg-gray-50 h-full flex flex-col items-center justify-start overflow-y-auto">
            <div className="w-full max-w-2xl">
                <div className="text-center mb-6">
                    <h1 className="text-3xl font-bold text-gray-800">Image Studio</h1>
                    <p className="text-gray-600 mt-2">Bring your ideas to life. Describe the image you want to create.</p>
                </div>
                
                <div className="mb-4">
                    <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g., A majestic lion wearing a crown, studio lighting, hyperrealistic"
                        className="llm-textarea w-full"
                        rows={3}
                        disabled={isLoading}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter' && !e.shiftKey) {
                                e.preventDefault();
                                handleGenerate();
                            }
                        }}
                    />
                     <button 
                        onClick={handleGenerate} 
                        className="llm-button w-full mt-2" 
                        disabled={isLoading || !prompt.trim()}
                    >
                        {isLoading ? 'Generating...' : '✨ Generate Image'}
                    </button>
                </div>
                
                {error && <p className="text-red-500 text-center mb-4">{error}</p>}
                
                <div className="w-full aspect-square bg-gray-200 rounded-lg flex items-center justify-center border border-gray-300 overflow-hidden relative shadow-inner">
                    {imageUrl && !error && (
                         <img src={imageUrl} alt={prompt} className="w-full h-full object-contain transition-opacity duration-300" style={{ opacity: isLoading ? 0.5 : 1 }} />
                    )}
                    
                    {isLoading && (
                        <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center text-white">
                             <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-white mb-4"></div>
                             <p className="font-semibold">Creating your masterpiece...</p>
                             <p className="text-sm opacity-80">This can take a moment.</p>
                        </div>
                    )}

                    {!isLoading && !imageUrl && (
                        <div className="text-gray-400 text-center p-4">
                            <p className="text-5xl mb-2">🖼️</p>
                            <p className="font-medium">Your generated image will appear here.</p>
                        </div>
                    )}
                </div>

                {!isLoading && imageUrl && (
                     <div className="mt-4 flex justify-center gap-3">
                        <button onClick={handleDownload} className="llm-button bg-gray-600 hover:bg-gray-700 active:bg-gray-800">
                           📥 Download
                        </button>
                         <button onClick={handleGenerate} className="llm-button">
                           🔄 Regenerate
                        </button>
                         <button onClick={handleShare} className="llm-button bg-green-600 hover:bg-green-700 active:bg-green-800" disabled={!navigator.share}>
                           📤 Share
                        </button>
                     </div>
                )}
            </div>
        </div>
    );
};