
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
/* tslint:disable */
import {AppDefinition} from './types';

export const APP_DEFINITIONS_CONFIG: AppDefinition[] = [
  {id: 'my_computer', name: 'Desktop', icon: '💻', color: '#e3f2fd', category: 'System'},
  {id: 'file_explorer', name: 'File Explorer', icon: '📁', color: '#f1f8e9', category: 'System'},
  {id: 'calendar_app', name: 'Calendar', icon: '🗓️', color: '#e8f0fe', category: 'Productivity'},
  {id: 'wallet_app', name: 'Wallet', icon: '💳', color: '#e0f2f1', category: 'Utilities'},
  {id: 'settings_app', name: 'Settings', icon: '⚙️', color: '#e7f3ff', category: 'System'},
  {id: 'trash_bin', name: 'Trash Bin', icon: '🗑️', color: '#ffebee', category: 'System'},
  {id: 'notepad_app', name: 'Notepad', icon: '📝', color: '#fffde7', category: 'Productivity'},
  {id: 'terminal_app', name: 'Terminal', icon: '⌨️', color: '#374151', category: 'Productivity'},
  {id: 'to_do_list_app', name: 'To-Do List', icon: '✅', color: '#E8F5E9', category: 'Productivity'},
  {id: 'notes_app', name: 'Notes', icon: '🗒️', color: '#FFFDE7', category: 'Productivity'},
  {id: 'keyword_researcher_app', name: 'Keyword Researcher', icon: '🔍', color: '#E3F2FD', category: 'Productivity'},
  {id: 'translator_app', name: 'Translator', icon: '🌍', color: '#e3f2fd', category: 'Productivity'},
  {id: 'seo_article_writer_app', name: 'SEO Article Writer', icon: '✍️', color: '#e8f5e9', category: 'Productivity'},
  {id: 'google_trends_app', name: 'Google Trends', icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Google_Trends_2017_logo.svg', color: '#e8f0fe', category: 'Web'},
  {id: 'gemini_lens', name: 'Gemini Lens', icon: '✨', color: '#F3E5F5', category: 'Productivity'},
  {id: 'gallery_app', name: 'Gallery', icon: '📷', color: '#e1f5fe', category: 'Media'},
  {id: 'image_studio', name: 'Image Studio', icon: '🖼️', color: '#E8EAF6', category: 'Media'},
  {id: 'web_browser_app', name: 'Chrome', icon: '🌐', color: '#e0f7fa', category: 'Web'},
  {id: 'calculator_app', name: 'Calculator', icon: '🧮', color: '#f5f5f5', category: 'Utilities'},
  {id: 'content_planner_app', name: 'Content Planner', icon: '📅', color: '#1a1a1a', category: 'Productivity'},
  {id: 'app_store', name: 'App Store', icon: '🛍️', color: '#FFD54F', category: 'System'},
  {id: 'video_generator', name: 'Video Generator', icon: '🎬', color: '#FF5722', category: 'Media'},
];


export const INITIAL_MAX_HISTORY_LENGTH = 0;

export const getSystemPrompt = (maxHistory: number): string => `
**Role:**
You are an AI that functions as the operating system logic for desktop simulation.
Your goal is to generate HTML content for the *main content area* of a window based on user interactions on a GUI.

**Instructions**
0.  **Available apps:** The computer has several apps that can be opened from home screen.
    - "Desktop": Details desktop system specifications in a google-y way. Do not include extra content like one that replicates the home app space.
    - "File Explorer": A classic file explorer interface to browse folders and files. It should contain folders like Documents, Pictures, Downloads, etc.
    - "Calendar": A smart calendar application to view dates, add events, and AI-generate daily schedules.
    - "Wallet": A digital wallet application with "Pay with Scan" functionality using camera, balance tracking, and transaction history.
    - "Notepad": Has a writable notepad, edit functionalities and saving functionalities here.
    - "To-Do List": A simple task management application to add, complete, and delete tasks.
    - "Notes": A basic note-taking application for quick thoughts and ideas.
    - "Keyword Researcher": An app to find popular keywords related to a topic using Google Search grounding.
    - "Google Trends": Framework handled. Do not generate content.
    - "Settings": This is a regular app generated by you, not the OS-level parameters panel. It has usual settings like display, sound, network, privacy, wallpaper, etc.
    - "Trash Bin": Has example files that can be deleted.
    - "Chrome": Goes into web browsing mode. When in Chrome, the user is surfing the web.
    - "Calculator": Has a calculator widget with rectangular layout.
    - "Terminal": Activates the command line interface.
    - "Image Studio": Framework handled. Do not generate content.
    - "Translator": Framework handled. Do not generate content.
    - "SEO Article Writer": Framework handled. Do not generate content.
    - "Gallery": Framework handled. Do not generate content.
    - "Gemini Lens": Framework handled. Do not generate content.
1.  **HTML output:** Your response MUST be ONLY HTML for the content to be placed inside a parent container.
    - DO NOT include \`\`\`html, \`\`\`\`, \`<html>\`, \`<body>\`, or any outer window frame elements. These are handled by the framework.
    - Do NOT include \`<style>\` tags.
2.  **Styling:** Use the provided CSS classes strictly (llm-button, llm-text, llm-title, llm-input, llm-textarea, llm-container, llm-row, llm-label, icon).
3.  **Interactivity:** ALL interactive elements MUST have a \`data-interaction-id\` attribute.
4.  **Special instructions for embedding Google Maps:** Use simple format: \`src="https://www.google.com/maps?q=YOUR_QUERY_HERE&output=embed"\`
5.  **Interaction History:** You will receive a history of the last N user interactions (N=${maxHistory}).
6.  **Web Browser Links:** For links that navigate to a new URL, use data-interaction-type="url_navigation" and data-interaction-value="THE_URL".
`;
